### ISSUE TITLE
The plugin didn't work

### ISSUE THREAD

**Issue by NanSanOBA** [CCrashCup/FoV-Sphere#1]
Hi author, I'm not sure if I'm using it correctly, the plugin isn't working. I'm using blender 3.3.10 if it's possible could you have a video link to guide me on how it's being used, thank you very much.

**Comment by flyingsaucer0001** [comment]
Plugin works perfectly I've tried personally with all Blender Long Term Support version starting from 3.3.1 LTS up to 3.3.11 LTS, mayber you need to understand how to use. If plugin it's added in Panel ( Press 'N' ) it just works.

**Comment by CCrashCup** [comment]
I added a step by step instruction section to the README.md. It does not explain anything, but it should be easier to follow.
